### ISSUE TITLE
Python target version for Black formatter is not up-to-date

### ISSUE THREAD

**Issue by andreistr21** [pdyba/lambdalizator#90]

**Comment by andreistr21** [comment]
This commit [d4a17c2](https://github.com/andreistr21/lambdalizator/commit/d4a17c2e41a4d673e4ccac28a93024e10d8f8c5f) fixes this.

**Comment by redlickigrzegorz** [comment]
> This commit [d4a17c2](https://github.com/andreistr21/lambdalizator/commit/d4a17c2e41a4d673e4ccac28a93024e10d8f8c5f) fixes this.

We should use `py39` as this is the version that we use in Lambdalizator as a default one 😉 

Let's adjust it within #84.

**Comment by andreistr21** [comment]
Solved in [updates target version for black to py39](https://github.com/pdyba/lambdalizator/commit/62b3650ee36325768651fcec1d15b5732ed71160)

**Comment by andreistr21** [comment]
Solved in [updates target version for black to py39](https://github.com/pdyba/lambdalizator/commit/62b3650ee36325768651fcec1d15b5732ed71160)
